### PR TITLE
MNT Use GitHub Actions CI

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/gha-ci/issues/11<br /><br />Workflow run https://github.com/creative-commoners/recipe-plugin/actions?query=branch%3Apulls%2F1.7%2Fmodule-standards

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Don't need cron for this one since it has no tests. CI is effectively only running linting.
Wouldn't hurt to disable the unused parts via inputs as well to reduce the number of runners needed.

**Comment by emteknetnz** [comment]
No need to set inputs, dynamic matrix generation does that automatically in gha-generate-matrix

**Comment by GuySartorelli** [comment]
Fair point

**Comment by emteknetnz** [comment]
Would prefer to keep cron on these for standardization i.e in the future we'll never need to investigate "why hasn't this build run for 6 months?".  The amount of resources this will consume is minimal.

**Review by GuySartorelli — APPROVED** [review]

**Pull request merged**
