### PR TITLE
Remove unnecessary methods from trait, adds Composer 2.3 compatibility

### PR DESCRIPTION
**Pull request by Seldaek**
I believe this should fix things reported in https://github.com/silverstripe/recipe-plugin/issues/18

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Tha is for the contribution @Seldaek. We can't remove these methods without making it a major release since `RecipeCommandBehaviour` is part of the public API. It's unlikely to be used in other projects but we can't rule it out.

**Comment by dhensby** [comment]
@GuySartorelli - as @Seldaek points out in #18, these methods exist on the base command, so removing them from the trait shouldn't be too big a deal? (unless the signatures are different, I suppose)

But I guess if we need to release a major version to support 2.3, then so be it?

**Comment by GuySartorelli** [comment]
The BC concern is if someone else is using the trait for some class that doesn't extend `BaseCommand`. Unlikely, but something that bears considering and pointing out as a possibility. Though I guess since they're abstract, they'll have some concrete implementation in their class anyway, so maybe that doesn't matter? 🤔

**Comment by dhensby** [comment]
Yep, if they are abstract they will have had to implement them to get them working now.

In terms of major release, what are the blockers to v2 being tagged?

**Comment by Seldaek** [comment]
> Though I guess since these declarations are abstract, they'll have some concrete implementation in their class anyway, so maybe that doesn't matter? 

Yeah IMO this seems really fine to do even as a minor release, but up to you.

**Review by GuySartorelli — APPROVED** [review]

**Comment by maxime-rainville** [comment]
I tested this PR locally. It fixes the error when using composer 2.3.2. It also doesn't break anything when using composer 2.2.6 or 1.10.25. I'll try doing a deployment to our platform to make sure things work there as well. Presuming that works well, I'm inclined to tag merge this PR and tag a release to ship it.

**Review by maxime-rainville — APPROVED** [review]
Confirmed this fixes the issue and doesn't break anything anywhere else.

I'll merge this and tag version 1.6.0

**Pull request merged**
